periods:
  - period1:
      startdate: !!timestamp 2022-12-01
      enddate: !!timestamp 3000-01-01
      excludedates:
        - !!timestamp 2023-01-01
        - !!timestamp 2023-02-01
      excludedays:
        - !!int 6
        - !!int 7
      rewrite: !!bol no
