periods:
  - period:
      start_date: !!timestamp 2023-08-01
      end_date: !!timestamp 3000-01-01
      # Дни недели: начинаются с 0 - пн
      exclude_days:
        - !!int 5
        - !!int 6
  - period:
      start_date: !!timestamp 2023-08-05
      end_date: !!timestamp 2023-08-05

